Vogeltelling.API/Vogeltelling.Web/Models/Bird.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Vogeltelling.Web.Models
{
    public class Bird
    {

        //[ScaffoldColumn(false)]
        //[Key]
        [Required]
        public Guid BirdId { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        public string PhotoUrl { get; set; }


    }
}

Vogeltelling.API/Vogeltelling.Web/Controllers/BirdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Vogeltelling.Web.Models;
using Vogeltelling.Web.Repositories;

namespace Vogeltelling.Web.Controllers
{
    public class BirdController : Controller
    {
        private readonly IBirdRepository _birdRepository;

        public BirdController(IBirdRepository birdRepository)
        {
            _birdRepository = birdRepository;
        }

        
        public IActionResult Index()
        {

            var birds = _birdRepository.GetAllBirds() as List<Bird>;
            return View(birds);
        }

        public IActionResult Details(Guid id)
        {
            var bird = _birdRepository.GetBirdById(id);
            if (bird == null) return NotFound();
            return View(bird);
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(Guid id)
        {
            var bird = _birdRepository.GetBirdById(id);
            if (bird == null) return NotFound();
            return View(bird);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public IActionResult Edit(Bird bird) //[Bind("BirdId, Name, Description, PhotoUrl")]
        {
            try
            {
                var succes = _birdRepository.EditBird(bird);
                if (succes)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound();
                }
                
            }
            catch (Exception)
            {
                return NotFound();
            }

        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            try
            {
                return View();
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public IActionResult Create(Bird bird)
        {
            try
            {
                var succes = _birdRepository.CreateBird(bird);
                if (succes)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return NotFound();
                }
            }
            catch (Exception)
            {
                return NotFound();
            }
        }

        [Authorize(Roles = "Administrator")]
        public IActionResult Delete(Guid id)
        {
            var bird = _birdRepository.GetBirdById(id);
            if (bird == null) return NotFound();
            return View(bird);
        }

        // POST: /Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult DeleteConfirmed(Guid id)
        {
            _birdRepository.DeleteBird(id);
            return RedirectToAction("Index");
        }


    }
}

Vogeltelling.API/Vogeltelling.Web/Views/Bird/Create.cshtml
@model Vogeltelling.Web.Models.Bird

@{
    ViewData["Title"] = "Create";
}

<h2>Nieuwe vogel toevoegen</h2>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" maxlength="55"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" maxlength="512"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhotoUrl" class="control-label"></label>
                <input asp-for="PhotoUrl" class="form-control" maxlength="255"/>
                <span asp-validation-for="PhotoUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Vogeltelling.API/Vogeltelling.Web/Views/Bird/Delete.cshtml
@model Vogeltelling.Web.Models.Bird

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Bird</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.BirdId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BirdId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhotoUrl)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhotoUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Vogeltelling.API/Vogeltelling.Web/Views/Bird/Details.cshtml
@model Vogeltelling.Web.Models.Bird

@{
    ViewData["Title"] = "Details";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>

<main>
    <div class="Detail">
        <hr />

        <img src="@Html.DisplayFor(model => model.PhotoUrl)" alt="@Html.DisplayFor(model => model.Name)" />
        <p> @Html.DisplayFor(model => model.Description)</p>



    </div>
    <div>
        @* ACTIONLINK: EERSTE: Woord    TWEEDE: ActionName *@
        @if (ViewContext.HttpContext.User.IsInRole("Administrator"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.BirdId });
    <scheiding>|</scheiding>
    @Html.ActionLink("Delete", "Delete", new { id = Model.BirdId })
    <scheiding>|</scheiding>
}

        <a asp-action="Index">Back to List</a>
    </div>
</main>

Vogeltelling.API/Vogeltelling.Web/Views/Bird/Edit.cshtml
@model Vogeltelling.Web.Models.Bird

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Bird</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>

                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.BirdId)

                @*<input type="hidden" asp-for="BirdId" />*@

            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PhotoUrl" class="control-label"></label>
                <input asp-for="PhotoUrl" class="form-control" />
                <span asp-validation-for="PhotoUrl" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Vogeltelling.API/Vogeltelling.Web/Views/Bird/Index.cshtml
@model IEnumerable<Vogeltelling.Web.Models.Bird>

@*@section AddToHead{
    <link href="@Url.Content("~/css/StyleSheet.css")" rel="stylesheet" type="text/css" />
}*@

@{
    ViewData["Title"] = "Index";
}

<main>
    <h2>All Birds</h2>

    @if (ViewContext.HttpContext.User.IsInRole("Administrator"))
    {
        @Html.ActionLink("Create", "Create")
    }

    <div class="Vogels">
        @foreach (var item in Model)
        {


            @* URL ACTION: EERSTE: HTML PAGINA     TWEEDE: MAP WAAR PAGINA IN STAAT*@
            <div class="Vogels__vogel">
                <a href="@Url.Action("Details", "Bird", new { id = item.BirdId })">
                    <figure>
                        <img src=" @Html.DisplayFor(modelItem => item.PhotoUrl)" alt="@Html.DisplayFor(modelItem => item.Name)">
                        <figcaption>@Html.DisplayFor(modelItem => item.Name)</figcaption>
                    </figure>
                </a>
            </div>

        }
    </div>
</main>